# Generated by Django 4.2.6 on 2023-10-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='cateqoriya adi')),
            ],
            options={
                'verbose_name': 'cateqoriya adi',
                'verbose_name_plural': 'cateqoriya adlari',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='İtem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='daxil edilen ')),
                ('color', models.CharField(max_length=255, verbose_name='daxil edilen reng')),
                ('price', models.CharField(max_length=255, verbose_name='daxil edilen qiymey')),
                ('count', models.CharField(max_length=255, verbose_name='daxil edilen say')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.category')),
            ],
            options={
                'verbose_name': 'daxil edilen',
                'verbose_name_plural': 'daxil edilenler',
                'ordering': ('name',),
            },
        ),
    ]
