# Generated by Django 4.2.6 on 2023-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i̇tem',
            name='count',
            field=models.IntegerField(verbose_name='daxil edilen say'),
        ),
        migrations.AlterField(
            model_name='i̇tem',
            name='price',
            field=models.FloatField(verbose_name='daxil edilen qiymey'),
        ),
    ]
