# Generated by Django 4.2.5 on 2023-10-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_i_tem_count_alter_i_tem_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='İtem',
            new_name='Item',
        ),
    ]
