# Generated by Django 4.2.6 on 2023-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_i_tem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='meslul sekili'),
        ),
    ]
